baseurl = "https://gaos.netlify.com/"
languageCode = "en-us"
title = "Genome Analysis & Statistics"
theme = "hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Week 1: Introduction"
    url = "/week-1/"
[[menu.main]]
    name = "Week 2: Summary statistics"
    url = "/week-2/"
[[menu.main]]
    name = "Week 3: Sampling distributions"
    url = "/week-3/"
[[menu.main]]
    name = "Week 4: Probability"
    url = "/week-4/"
    
    [[menu.main]]
    name = "Week 5: Hypothesis testing"
    url = "/week-5/"

[params]
    description = "R notebooks created for students taking the course in Spring 2018 at Aarhus University."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "monokai"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

